# Generated by Django 5.1.15 on 2026-04-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(default="PathLab", max_length=80)),
                (
                    "tagline",
                    models.CharField(
                        default="The place where your next exam, career, or first line of code begins.",
                        max_length=200,
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Your entrance exam, your upskill, your kid's first AI project — one place.",
                        max_length=200,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="Built for Nepal. Trusted globally. Clean, fast, non-stuffy.",
                        max_length=300,
                    ),
                ),
                (
                    "hero_cta_label",
                    models.CharField(default="Try for free", max_length=40),
                ),
                ("promo_active", models.BooleanField(default=True)),
                (
                    "promo_text",
                    models.CharField(
                        default="15% off launch — ends this Friday", max_length=200
                    ),
                ),
                (
                    "promo_cta_label",
                    models.CharField(default="Claim discount", max_length=40),
                ),
                (
                    "promo_cta_url",
                    models.CharField(default="/subscriptions/", max_length=200),
                ),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="TrustSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.CharField(max_length=300)),
                (
                    "icon",
                    models.CharField(
                        default="spark",
                        help_text="shape token: spark, circle, square, triangle",
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
