# Generated by Django 5.1.15 on 2026-04-18 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "pillar",
                    models.CharField(
                        choices=[
                            ("entrance", "Entrance Prep"),
                            ("tech", "Tech Upskilling"),
                            ("kids", "Kids' Summer Camp"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "shape",
                    models.CharField(
                        choices=[
                            ("circle", "Circle"),
                            ("square", "Square"),
                            ("triangle", "Triangle"),
                            ("hexagon", "Hexagon"),
                        ],
                        default="circle",
                        max_length=20,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="green",
                        help_text="tailwind token: green (Entrance), blue (Tech), neon (Kids)",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SuccessStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "value",
                    models.CharField(
                        help_text="e.g. '12,000+' or '94%'", max_length=50
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("scratch", "From Scratch"),
                            ("experienced", "For Experienced"),
                            ("kid", "Kid-friendly"),
                        ],
                        default="scratch",
                        max_length=20,
                    ),
                ),
                ("duration_weeks", models.PositiveIntegerField(default=4)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="courses/"),
                ),
                (
                    "price_npr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_free", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="courses.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                (
                    "student_title",
                    models.CharField(
                        blank=True, help_text="e.g. CMAT 2024 topper", max_length=100
                    ),
                ),
                ("quote", models.CharField(max_length=280)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("is_video", models.BooleanField(default=False)),
                ("video_url", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="courses.course",
                    ),
                ),
            ],
        ),
    ]
