# Generated by Django 5.1.15 on 2026-04-19 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_badge_enrollment_module_lesson_lessonprogress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Optional direct upload. Used if no embed URL is set.",
                null=True,
                upload_to="lessons/videos/",
            ),
        ),
        migrations.CreateModel(
            name="LessonResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("slide", "Slides"),
                            ("code", "Source / ZIP"),
                            ("other", "Other"),
                        ],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="lessons/resources/")),
                (
                    "is_free_preview",
                    models.BooleanField(
                        default=False,
                        help_text="If true, anyone can download — even without a subscription.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
