# Generated by Django 5.1.15 on 2026-04-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_instructor_course_instructor_coursereview_lessonnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="review_notes",
            field=models.TextField(
                blank=True, help_text="Staff feedback for the instructor."
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending review"),
                    ("approved", "Approved"),
                    ("changes_requested", "Changes requested"),
                ],
                default="approved",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
