# Generated by Django 5.1.15 on 2026-04-19 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "percent_off",
                    models.PositiveSmallIntegerField(
                        default=10, help_text="0–100 — percentage discount."
                    ),
                ),
                (
                    "max_redemptions",
                    models.PositiveIntegerField(default=0, help_text="0 = unlimited."),
                ),
                ("times_redeemed", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="subscription",
            name="discounted_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Final charged price after coupon. Null = plan's list price.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="subscriptions.coupon",
            ),
        ),
    ]
