# Generated by Django 5.1.15 on 2026-04-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_coupon_subscription_discounted_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="initiated",
                max_length=20,
            ),
        ),
    ]
