# Generated by Django 5.1.15 on 2026-04-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="plans",
            field=models.ManyToManyField(
                blank=True,
                help_text="Restrict to specific plans. Leave empty to apply to all plans.",
                related_name="coupons",
                to="subscriptions.plan",
            ),
        ),
    ]
